### ISSUE TITLE
Error with download button with Fairfax County, VA ARRESTS 2021 data

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/OPD_Explorer#32]
During this part of the code:
```
logger.debug("Checking for preview")
if st.session_state["preview"] is not None:
    logger.debug("Preview found")
    st.divider()
    st.subheader("Preview")
    logger.debug(f"Creating preview table for table of length {len(st.session_state['preview'])}:")
    logger.debug(st.session_state["preview"])
    st.dataframe(data=st.session_state["preview"])
    logger.debug('Preview created')
```

We get the following output:
```
Checking for preview
Preview found
Creating preview table for table of length 20:
    OBJECTID   Arrest ID  Case Number     Arrest Date  Arrest Time  ...   DISTRICT_1                           BOS Web Address  BOS Phone Number                    BOS Name  Year
0     183583  2021003388                4/1/2021 0:00         1640  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
1     183584  2021002914  20210780205  3/19/2021 0:00         2254  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
2     183585  2021006789  20211390103  5/19/2021 0:00         1151  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
3     183586  2021003002  20210810087  3/22/2021 0:00         1113  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
4     183587  2021003389                4/1/2021 0:00         1642  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
5     183588  2021002914  20210780205  3/19/2021 0:00         2254  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
6     183589  2021006789  20211390103  5/19/2021 0:00         1151  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
7     183590  2021003002  20210810087  3/22/2021 0:00         1113  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
8     183591  2021003466  20210940023   4/4/2021 0:00          235  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
9     183592  2021002955  20210790031  3/20/2021 0:00          712  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
10    183593  2021006789  20211390103  5/19/2021 0:00         1151  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
11    183594  2021003002  20210810087  3/22/2021 0:00         1113  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
12    183595  2021003467  20210940023   4/4/2021 0:00          233  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
13    183596  2021002956  20210790175  3/20/2021 0:00         2110  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
14    183597  2021006789  20211390103  5/19/2021 0:00         1151  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
15    183598  2021003002  20210810087  3/22/2021 0:00         1113  ...  HUNTER MILL   http://www.fairfaxcounty.gov/huntermill/     703-478-0283            Walter L. Alcorn  2021   
16    183599  2021001429  20210390192   2/8/2021 0:00         1645  ...  SPRINGFIELD  http://www.fairfaxcounty.gov/springfield/     703-451-8873  Patrick S. ""Pat"" Herrity  2021   
17    183600  2021003522                4/5/2021 0:00         1730  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
18    183601  2021003522                4/5/2021 0:00         1730  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   
19    183602  2021003593  20210960191   4/6/2021 0:00         1716  ...        SULLY        http://www.fairfaxcounty.gov/sully/     703-814-7100              Kathy L. Smith  2021   

[20 rows x 35 columns]
2023-06-03 11:52:12.156 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\matth\repos\OPD_Explorer\opd_download_page.py", line 225, in <module>
    st.dataframe(data=st.session_state["preview"])
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\streamlit\runtime\metrics_util.py", line 332, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\streamlit\runtime\metrics_util.py", line 332, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\streamlit\elements\arrow.py", line 197, in marshall
    proto.data = type_util.data_frame_to_bytes(df)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\streamlit\type_util.py", line 757, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\table.pxi", line 3681, in pyarrow.lib.Table.from_pandas
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\pyarrow\pandas_compat.py", line 611, in dataframe_to_arrays
    arrays = [convert_column(c, f)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\pyarrow\pandas_compat.py", line 611, in <listcomp>
    arrays = [convert_column(c, f)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\streamlit\Lib\site-packages\pyarrow\pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\array.pxi", line 323, in pyarrow.lib.array
  File "pyarrow\array.pxi", line 83, in pyarrow.lib._ndarray_to_array
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc96' in position 8: surrogates not allowed
```
Error occurs during the line:
`    st.dataframe(data=st.session_state["preview"])`

There must be something in the table that streamlit doesn't like when it tries to display

**Comment by sowdm** [comment]
This solves the issue by replacing non-ASCII characters with ''
https://stackoverflow.com/questions/36340627/remove-non-ascii-characters-from-pandas-column
